### ISSUE TITLE
Readability colour change request

### ISSUE THREAD

**Issue by Atukii** [TakenMC/Catppuccin#1]
Love the theme, but a few of the elements are incredibly hard to read. I appreciate it might be a little nit-picky and it might not follow the design of the theme itself but if it's not a difficult fix it would be quite useful.

Two examples to illustrate using Frappe theme;

![image](https://github.com/TakenMC/Catppuccin/assets/34585532/7e4112bd-2695-47a0-9652-a220ae031622)
The little green circle to indicate you're in the voice chat has a small speaker icon, in the current colour scheme the icon itself is nearly invisible.

![image](https://github.com/TakenMC/Catppuccin/assets/34585532/4eaaf945-4ebc-43fa-8c41-15d859610db1)
Similarly to the above, when you hover over the Voice Connected there is a popup using the same colours, the delay is usually displayed but here it's barely visible.

I would propose to change the inner element colours to something more contrasting with the green perhaps `#2D2D3D` or `#252635`

**Comment by TakenMC** [comment]
The pallets and colors are pulled from the original [catppuccin discord repo](https://github.com/catppuccin/discord) so you will have to contact them about this

**Comment by TakenMC** [comment]
this has been updated using the  latest pallet from catppuccin and it should  be on the replugged store soon
